echo 'CACHE MANIFEST'
echo -n '# autogenerated '
date
echo
echo 'CACHE:'
cd static
find data/img -type f | sed 's/^/\//'

# don't cache these yet -- they change too often in development
#find data/units -type f | sed 's/^/\//'
#find data/factions -type f | sed 's/^/\//'

echo
echo 'NETWORK:'
echo '*'

